# Generated by Django 3.1 on 2020-09-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_doc_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_username', models.CharField(max_length=100)),
                ('doctor_username', models.CharField(max_length=100)),
                ('auth_key', models.CharField(max_length=100)),
            ],
        ),
    ]
