# Generated by Django 3.1 on 2020-11-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_patientdocconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdocconfig',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='patientdocconfig',
            name='patient_username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='Aadhar_Number',
            field=models.IntegerField(help_text='12 digit unique Aadhar Number'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='phone',
            field=models.CharField(help_text='10 digit Mobile Number', max_length=40),
        ),
    ]
