# Generated by Django 3.1 on 2020-09-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_patient_doc_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=100)),
                ('doctor_notes', models.TextField(max_length=1000)),
                ('medications', models.TextField(max_length=1000)),
            ],
        ),
    ]
