# Generated by Django 3.1 on 2020-11-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20201107_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdocconfig',
            name='patient_username',
        ),
        migrations.AddField(
            model_name='patientdocconfig',
            name='patient_id',
            field=models.IntegerField(default=0),
        ),
    ]
