# Generated by Django 3.1 on 2020-11-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20201107_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdocconfig',
            name='patient_id',
            field=models.CharField(max_length=100),
        ),
    ]
