# Generated by Django 3.1 on 2020-11-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_auto_20201107_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdocconfig',
            name='patient_id',
        ),
    ]
