# Generated by Django 3.1 on 2020-08-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_age', models.ImageField(upload_to='')),
                ('doctor_diagnosis', models.CharField(max_length=50)),
                ('doctor_notes', models.TextField(max_length=1000)),
                ('doctor_prescription', models.TextField(max_length=1000)),
            ],
        ),
    ]
