# Generated by Django 3.1 on 2020-08-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
