# Generated by Django 3.1 on 2020-08-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0003_report_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_age', models.IntegerField()),
                ('patient_contact', models.CharField(max_length=15)),
                ('patient_address', models.CharField(max_length=200)),
                ('password_share', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
