# Generated by Django 3.1 on 2020-08-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0004_register_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_patient',
            name='patient_username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
