# Generated by Django 3.1 on 2020-08-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0005_register_patient_patient_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_username', models.CharField(max_length=50)),
                ('doctor_name', models.CharField(max_length=50)),
                ('doctor_contact', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
