# Generated by Django 3.1 on 2020-08-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0006_register_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_username', models.CharField(max_length=50)),
                ('patient_age', models.IntegerField()),
                ('doctor_name', models.CharField(max_length=50)),
                ('doctor_notes', models.TextField(max_length=1000)),
                ('doctor_prescription', models.TextField(max_length=500)),
            ],
        ),
    ]
