# Generated by Django 3.0.7 on 2020-10-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
    ]
