# Generated by Django 3.0.7 on 2020-10-21 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centralapp', '0002_auto_20201020_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=30)),
                ('Specialisation', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=40)),
                ('City', models.CharField(max_length=30)),
                ('Registration_Number', models.CharField(max_length=40)),
                ('Registration_Council', models.CharField(max_length=100)),
                ('Registration_year', models.IntegerField()),
                ('Degree', models.CharField(max_length=100)),
                ('College', models.CharField(max_length=100)),
                ('Year_of_completion', models.IntegerField()),
                ('Profile_pic', models.ImageField(default='defaultprofilepic.jpg', upload_to='doctors_profile_pictures')),
                ('Medical_registration_proof', models.FileField(upload_to='DoctorRegProofs')),
                ('Current_place_of_work', models.CharField(max_length=30)),
                ('Aadhar_Number', models.IntegerField(help_text='Identity Proof')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('address', models.TextField(max_length=500)),
                ('phone', models.CharField(max_length=40)),
                ('emergency_contact', models.IntegerField(blank=True)),
                ('profession', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('profile_pic', models.ImageField(default='defaultprofilepic.jpg', upload_to='patients_profile_pictures')),
                ('Aadhar_Number', models.IntegerField(help_text='Identity Proof')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Height_in_Centimeters', models.CharField(max_length=100)),
                ('Weight_in_kilograms', models.CharField(max_length=100)),
                ('Allergies', models.TextField(max_length=30)),
                ('Smoker_or_not', models.CharField(max_length=30)),
                ('Chronic_conditions', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
