# Generated by Django 3.0.7 on 2020-10-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralapp', '0003_auto_20201021_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='emergency_contact',
            field=models.CharField(max_length=40),
        ),
    ]
