# Generated by Django 3.0.7 on 2020-10-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralapp', '0004_auto_20201021_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='Aadhar_Number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='Profile_pic',
            field=models.ImageField(default='patients_profile_pictures/defaultprofilepic.jpg', upload_to='doctors_profile_pictures'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='Aadhar_Number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_pic',
            field=models.ImageField(default='patients_profile_pictures/defaultprofilepic.jpg', upload_to='patients_profile_pictures'),
        ),
    ]
