# Generated by Django 3.0.7 on 2020-11-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='Aadhar_Number',
            field=models.IntegerField(help_text='12 digit unique Aadhar Number'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='phone',
            field=models.CharField(help_text='10 digit Mobile Number', max_length=40),
        ),
        migrations.AlterField(
            model_name='patientvitals',
            name='Chronic_conditions',
            field=models.CharField(help_text='Your current long term diseases. <br>Ex. High BP, Diabetes etc', max_length=30),
        ),
        migrations.AlterField(
            model_name='patientvitals',
            name='Height_in_Centimeters',
            field=models.CharField(help_text='Height in centimeters', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientvitals',
            name='Weight_in_kilograms',
            field=models.CharField(help_text='Weight in kilograms', max_length=100),
        ),
    ]
