# Generated by Django 3.1 on 2020-11-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('diagnosis', models.CharField(max_length=500)),
                ('Symptoms', models.CharField(max_length=500)),
                ('medication', models.CharField(max_length=500)),
                ('additional_precautions', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='Aadhar_Number',
            field=models.IntegerField(help_text='12 digit unique Aadhar Number'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='phone',
            field=models.CharField(help_text='10 digit Mobile Number', max_length=40),
        ),
        migrations.AlterField(
            model_name='patientvitals',
            name='Chronic_conditions',
            field=models.CharField(help_text='Your current long term diseases. <br>Ex. High BP, Diabetes etc', max_length=30),
        ),
        migrations.AlterField(
            model_name='patientvitals',
            name='Height_in_Centimeters',
            field=models.CharField(help_text='Height in centimeters', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientvitals',
            name='Weight_in_kilograms',
            field=models.CharField(help_text='Weight in kilograms', max_length=100),
        ),
    ]
