# Generated by Django 3.1 on 2020-09-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_details',
            name='usertype',
            field=models.CharField(default='patient', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
