# Generated by Django 3.1 on 2020-09-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20200909_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_details',
            name='auth_key',
            field=models.TextField(default='123', max_length=100),
        ),
    ]
