# Generated by Django 3.1 on 2020-11-06 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20201106_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='patient_name',
        ),
    ]
