# Generated by Django 3.1 on 2020-09-14 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_details_auth_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_details',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient_details',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient_details',
            name='bgroup',
        ),
        migrations.RemoveField(
            model_name='patient_details',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='patient_details',
            name='mobile',
        ),
    ]
