# Generated by Django 3.1 on 2020-11-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patientprofile_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreports',
            name='labreportfile',
            field=models.FileField(upload_to=''),
        ),
    ]
