# Generated by Django 3.1 on 2020-09-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20200915_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_details',
            name='auth_key',
            field=models.CharField(default='123', max_length=100),
        ),
    ]
