# Generated by Django 3.1 on 2020-11-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20201107_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreports',
            name='labreportfile',
            field=models.FileField(upload_to='lab_reports'),
        ),
    ]
