# Generated by Django 3.1 on 2020-09-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20200915_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_p', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=10000)),
            ],
        ),
    ]
